"""`python scripts/isa_evidence.py` — render the model track's measured
results as markdown, for the ISA design document to cite.

The design document scores candidate instructions against both tracks'
measurements. This renders the half that is already measured, straight from
`results/*.json`, so a number quoted in the document cannot drift from the
number the descent actually produced.

**Rendering only.** It decides nothing about which candidate wins and adds
no interpretation beyond what `DEFENSE.md` already records. The one caveat
it prints is the caveat that already travels with the headline result: the
largest saving sits at a perplexity nobody deploys.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"


def load(name: str) -> dict:
    path = RESULTS / name
    if not path.exists():
        raise SystemExit(f"missing {path} — run scripts/descent.py first")
    return json.loads(path.read_text())


def fisher_table(descent: dict) -> str:
    scores = descent["fisher_scores"]
    order = descent["descent_order"]
    lines = [
        "| Role | Fisher score | Descent order |",
        "|---|---|---|",
    ]
    for role in sorted(scores, key=lambda r: -scores[r]):
        lines.append(f"| {role} | {scores[role]:.3e} | {order.index(role) + 1} |")
    return "\n".join(lines)


def matched_table(matched: dict) -> str:
    lines = [
        "| Perplexity budget | Uniform bytes | Mixed bytes | Saving | Mixed allocation |",
        "|---|---|---|---|---|",
    ]
    for row in matched["rows"]:
        alloc = ", ".join(f"{k}={v}" for k, v in sorted(row["mixed_alloc"].items()))
        lines.append(
            f"| {row['budget_ppl']} | {row['uniform_bytes'] / 1e6:.1f} MB | "
            f"{row['mixed_bytes'] / 1e6:.1f} MB | {row['saving_pct']:.1f}% | {alloc} |"
        )
    return "\n".join(lines)


def main() -> int:
    descent = load("descent.json")
    matched = load("matched_accuracy.json")

    fp32 = descent["fp32_ppl"]
    uni = descent["uniform_int4"]
    savings = [r["saving_pct"] for r in matched["rows"]]

    print("<!-- generated by scripts/isa_evidence.py — do not edit by hand -->\n")
    print("## Model-track evidence\n")
    print(
        f"GPT-2 small, WikiText-2, {descent['n_windows']}-window subset, "
        f"group size {descent['group_size']}. fp32 baseline perplexity "
        f"**{fp32:.2f}**, measured noise floor "
        f"**{descent['noise_floor_spread']:.1f}** over repeats — every "
        f"difference below is signal, not variance.\n"
    )
    print(
        f"Uniform INT4 over transformer weights: perplexity **{uni['ppl']:.2f}** "
        f"(+{(uni['ppl'] / fp32 - 1) * 100:.1f}%) at "
        f"**{uni['bytes'] / 1e6:.1f} MB**.\n"
    )

    print("### Per-role sensitivity\n")
    print(fisher_table(descent) + "\n")
    print(
        "Fisher-diagonal scores order the descent. They are a sensitivity "
        "*ranking*, not a cost model — what a bit of precision costs in "
        "perplexity is measured, not predicted from these.\n"
    )

    print("### Accuracy-matched byte savings\n")
    print(matched_table(matched) + "\n")
    print(
        f"Mixed precision saves between **{min(savings):.1f}%** and "
        f"**{max(savings):.1f}%** of transformer-weight bytes at matched "
        f"accuracy.\n"
    )
    print(
        "**The caveat travels with the number.** The saving is zero at the "
        "tightest budget and largest where accuracy is worst — the widest "
        "figure sits at roughly twice the fp32 perplexity, which nobody "
        "deploys. Mixed precision does not dominate uniform INT4; it fills "
        "the gap the uniform ladder leaves between INT4 and INT3. Any ISA "
        "candidate justified by *runtime-variable precision* has to be "
        "justified against that, not against the headline percentage. "
        "See `DEFENSE.md`.\n"
    )

    print("### What is not measured yet\n")
    print(
        "- The roofline, decode throughput, and the NEON kernels. Any "
        "candidate scored on unpacking *cost* is currently scored on "
        "operation counts alone (`isa/harness.py`), which is a count, not a "
        "time. No candidate may be described as faster on this evidence.\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
